services:
  marzban:
    image: gozargah/marzban:v0.7.0
    env_file: .env.marzban
    command: bash -c "alembic upgrade head && python /code/marzban.py"
    environment:
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: "8002"
      YOUR_DOMAIN: ${DOMAIN}
    ports:
      - "8002:8002"
      - "8443:8433"
      - "2053:2053"
    volumes:
      - marz-storage:/code
      - ./marzban.py:/code/marzban.py
      - ./volumes/marzban:/var/lib/marzban
      - ./volumes/marzban/xray_config.json:/code/xray_config.json:rw
      - /etc/timezone:/etc/timezone:ro
  vpn_bot:
    image: free_vpn_bot
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app"
    volumes:
      - .:/usr/src/app
    command: python3 -m bot
    env_file:
      - ".env"
    depends_on:
      - marzban

volumes:
  marz-storage:
    driver: local